### ISSUE TITLE
Concepts: Declarative Multi-Stage Delivery still shows the super old shipyard format

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#1062]
When navigating through the docs, I found this example:
```
stages:
  - name: "dev"
    deployment_strategy: "direct"
    test_strategy: "functional"
  - name: "hardening"
    deployment_strategy: "blue_green_service"
    test_strategy: "performance"
  - name: "production"
    deployment_strategy: "blue_green_service"
    remediation_strategy: "automated"
```
at
https://keptn.sh/docs/concepts/delivery/

This example is not supported since Keptn 0.8, so a good while. 

# Definition of Done

- [ ] Rewrite https://keptn.sh/docs/concepts/delivery/ such that it fits the current shipyard concept
