### ISSUE TITLE
Problem with Docs about Keptn User Managed Delivery

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#955]
The docs of the [User Managed Delivery](https://keptn.sh/docs/0.9.x/continuous_delivery/deployment_helm/#user-managed-deployments-experimental) state that we need to add an `endpoints.yaml` file using `--all-stages`.
![image](https://user-images.githubusercontent.com/56065213/140040668-83578a4b-64c2-4c6c-91f2-c3216443367b.png)

Example:
```
deploymentURIsLocal:
  - "http://helloservice.podtatohead-hardening:80" 
```

However, there is no relationship defined between the actual stages and the endpoints.yaml. For instance, this endpoints.yaml would straight-away fail if your shipyard define a different stage or even multiple stages, e.g.:

```
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
            - name: "test"
              properties:
                teststrategy: "performance"
            - name: "evaluation"

    - name: "hardening"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "dev.delivery.finished"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
            - name: "release"

```

# Definition of Done

- [ ] Docs reflect that an endpoint.yaml with a correct URL definition is required for each stage
