### ISSUE TITLE
Keptn Quickstart does not work reliablly on WSL2 and 0.11.2

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#984]
I'm trying the current quickstart guide with 0.11.2, and it actually fails to start prometheus server when using WSL2. Reason - corrupted YAML file generated in https://github.com/keptn-contrib/prometheus-service/blob/master/eventhandling/configureEvent.go

```

onenashev@DT-4CJV1F3:~/tmp/keptn-quickstart$ kubectl logs -n monitoring prometheus-server-689d99d68d-7mdzw prometheus-server
ts=2021-12-10T16:24:03.241Z caller=main.go:444 level=info msg="Starting Prometheus" version="(version=2.31.1, branch=HEAD, revision=411021ada9ab41095923b8d2df9365b632fd40c3)"
ts=2021-12-10T16:24:03.241Z caller=main.go:449 level=info build_context="(go=go1.17.3, user=root@9419c9c2d4e0, date=20211105-20:35:02)"
ts=2021-12-10T16:24:03.241Z caller=main.go:450 level=info host_details="(Linux 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 prometheus-server-689d99d68d-7mdzw clients.dynatrace.org)"
ts=2021-12-10T16:24:03.241Z caller=main.go:451 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2021-12-10T16:24:03.241Z caller=main.go:452 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2021-12-10T16:24:03.242Z caller=web.go:542 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2021-12-10T16:24:03.242Z caller=main.go:839 level=info msg="Starting TSDB ..."
ts=2021-12-10T16:24:03.244Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
ts=2021-12-10T16:24:03.245Z caller=head.go:479 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2021-12-10T16:24:03.245Z caller=head.go:513 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=1.218µs
ts=2021-12-10T16:24:03.245Z caller=head.go:519 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2021-12-10T16:24:03.397Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=7ts=2021-12-10T16:24:03.397Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=1 maxSegment=7ts=2021-12-10T16:24:03.397Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=2 maxSegment=7ts=2021-12-10T16:24:03.397Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=3 maxSegment=7ts=2021-12-10T16:24:03.398Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=4 maxSegment=7ts=2021-12-10T16:24:03.398Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=5 maxSegment=7ts=2021-12-10T16:24:03.399Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=6 maxSegment=7ts=2021-12-10T16:24:03.399Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=7 maxSegment=7ts=2021-12-10T16:24:03.399Z caller=head.go:596 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=30.328µs wal_replay_duration=153.679442ms total_replay_duration=153.719163ms
ts=2021-12-10T16:24:03.419Z caller=main.go:866 level=info fs_type=EXT4_SUPER_MAGIC
ts=2021-12-10T16:24:03.419Z caller=main.go:869 level=info msg="TSDB started"
ts=2021-12-10T16:24:03.419Z caller=main.go:996 level=info msg="Loading configuration file" filename=/etc/config/prometheus.yml
ts=2021-12-10T16:24:03.421Z caller=kubernetes.go:284 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2021-12-10T16:24:03.421Z caller=kubernetes.go:284 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2021-12-10T16:24:03.421Z caller=kubernetes.go:284 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2021-12-10T16:24:03.422Z caller=kubernetes.go:284 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2021-12-10T16:24:03.422Z caller=kubernetes.go:284 level=info component="discovery manager notify" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2021-12-10T16:24:03.423Z caller=manager.go:968 level=error component="rule manager" msg="loading groups failed" err="/etc/config/alerting_rules.yml: 29:11: group \"helloservice podtatohead-hardening alerts\", rule 3, \"failing_request\": could not parse expression: 1:1: parse error: binary expression must contain only scalar and instant vector types"
ts=2021-12-10T16:24:03.423Z caller=main.go:1022 level=error msg="Failed to apply configuration" err="error loading rules, previous rule set restored"
ts=2021-12-10T16:24:03.423Z caller=main.go:712 level=info msg="Stopping scrape discovery manager..."
ts=2021-12-10T16:24:03.423Z caller=main.go:726 level=info msg="Stopping notify discovery manager..."
ts=2021-12-10T16:24:03.423Z caller=main.go:748 level=info msg="Stopping scrape manager..."
ts=2021-12-10T16:24:03.423Z caller=main.go:708 level=info msg="Scrape discovery manager stopped"
ts=2021-12-10T16:24:03.423Z caller=main.go:742 level=info msg="Scrape manager stopped"
ts=2021-12-10T16:24:03.423Z caller=main.go:722 level=info msg="Notify discovery manager stopped"
ts=2021-12-10T16:24:03.424Z caller=manager.go:946 level=info component="rule manager" msg="Stopping rule manager..."
ts=2021-12-10T16:24:03.424Z caller=manager.go:956 level=info component="rule manager" msg="Rule manager stopped"
ts=2021-12-10T16:24:03.426Z caller=notifier.go:601 level=info component=notifier msg="Stopping notification manager..."
ts=2021-12-10T16:24:03.426Z caller=main.go:923 level=info msg="Notifier manager stopped"
ts=2021-12-10T16:24:03.427Z caller=main.go:932 level=error err="error loading config from \"/etc/config/prometheus.yml\": one or more errors occurred while applying the new configuration (--config.file=\"/etc/config/prometheus.yml\")"
```

## References

* See https://keptn.slack.com/archives/CNRCGFU3U/p1639154344378200
* https://github.com/keptn-contrib/prometheus-service

**Comment by oleg-nenashev** [comment]
Looks like it is a compatibility issue in the code

* Configurator in the service: https://github.com/keptn-contrib/prometheus-service/blob/master/eventhandling/configureEvent.go
* Prometheus sources: https://github.com/prometheus/prometheus/blob/3e494eac714302d2bafc246a750409d9ffb39456/web/ui/module/codemirror-promql/src/parser/parser.ts#L230-L233 . No better diagnostics offered

**Comment by oleg-nenashev** [comment]
The expression is broken indeed:

>     expr: promhttp_metric_handler_requests_total{code!="200",job="helloservice-podtatohead-hardening"}[180s]>
      10

The generated file extracted from the POD:

```
groups:
- name: helloservice podtatohead-hardening alerts
  rules:
  - alert: http_response_time_seconds_main_page_sum
    expr: sum(rate(http_server_request_duration_seconds_sum{method="GET",route="/",status_code="200",job="helloservice-podtatohead-hardening"}[180s])/rate(http_server_request_duration_seconds_count{method="GET",route="/",status_code="200",job="helloservice-podtatohead-hardening"}[180s]))>0.4
    for: 10m
    labels:
      severity: webhook
      pod_name: helloservice-primary
      service: helloservice
      stage: hardening
      project: podtatohead
    annotations:
      summary: http_response_time_seconds_main_page_sum
      descriptions: Pod name {{ $labels.pod_name }}
  - alert: go_routines
    expr: go_goroutines{job="helloservice-podtatohead-hardening"}>30
    for: 10m
    labels:
      severity: webhook
      pod_name: helloservice-primary
      service: helloservice
      stage: hardening
      project: podtatohead
    annotations:
      summary: go_routines
      descriptions: Pod name {{ $labels.pod_name }}
  - alert: failing_request
    expr: promhttp_metric_handler_requests_total{code!="200",job="helloservice-podtatohead-hardening"}[180s]>
      10
    for: 10m
    labels:
      severity: webhook
      pod_name: helloservice-primary
      service: helloservice
      stage: hardening
      project: podtatohead
    annotations:
      summary: failing_request
      descriptions: Pod name {{ $labels.pod_name }}

```
